const BreweryConstants = {
  INITIAL_LOAD: "INITIAL_LOAD",
  ADD_BREWERY: "ADD_BREWERY",
  UPDATE_SELECTED_BREWERY: "UPDATE_SELECTED_BREWERY",
  UPDATE_BREWERY: "UPDATE_BREWERY",
  SORT_BREWERIES: "SORT_BREWERIES"
};

module.exports = BreweryConstants;
